name: 'Slack Notification'
description: 'Sending a message from actions to slack.'
inputs:
  webhook-url:  # id of input
    description: 'Webhook url'
    required: true
outputs:
  time: # id of output
    description: 'The time we receive'
runs:
  using: 'node12'
  main: 'dist/index.js'
